name: build library

on: push

jobs:
  build:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Build binary
        run: cargo build --release
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: wrap-vt100
          path: target/release/wrap-vt100
  upload-release:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wrap-vt100
      - name: Publish
        uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: wrap-vt100
